version: "3.9"

services:
  db:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-r00t}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
  php:
    image: indominus/symfony:latest
    volumes:
      - .:/app
    depends_on:
      - db
    deploy:
      mode: global
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx/templates:/etc/nginx/templates:ro
    depends_on:
      - php